# Generated by Django 5.0.3 on 2024-08-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
